# Generated by Django 5.2.4 on 2025-07-28 12:37

import django.core.validators
import django.db.models.deletion
import smart_selects.db_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='type', chained_model_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='description',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма(в рублях)'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
    ]
