# Generated by Django 5.2.4 on 2025-07-28 12:38

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_category_name_alter_moneyflow_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyflow',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='type', chained_model_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='entities.category', verbose_name='Категория'),
        ),
    ]
