# Generated by Django 5.2.4 on 2025-07-28 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_moneyflow_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyflow',
            name='date_of_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
