# Generated by Django 5.2.4 on 2025-07-28 13:11

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_moneyflow_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyflow',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, to='entities.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='entities.subcategory', verbose_name='Подкатегория'),
        ),
    ]
